name: Build Game Solution

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Checkout code
        uses: action/checkout@v3
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: |
          msbuild Game.sln / p:Configuretion-Release /p:Platform=x64 
      
